
[functions.lookup-memorial]
enabled = true
verify_jwt = true
import_map = "./functions/lookup-memorial/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/lookup-memorial/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/lookup-memorial/*.html" ]

[functions.persist-images]
enabled = true
verify_jwt = true
import_map = "./functions/persist-images/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/persist-images/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/persist-images/*.html" ]
