[functions.lookup-memorial]
enabled = true
verify_jwt = true
import_map = "./functions/lookup-memorial/deno.json"
entrypoint = "./functions/lookup-memorial/index.ts"

[functions.persist-images]
enabled = true
verify_jwt = true
import_map = "./functions/persist-images/deno.json"
entrypoint = "./functions/persist-images/index.ts"

[functions.cleanup-images]
enabled = true
verify_jwt = false # Recommended to be false for cron jobs
import_map = "./functions/cleanup-images/deno.json"
entrypoint = "./functions/cleanup-images/index.ts"